### ISSUE TITLE
Which licence?

### ISSUE THREAD

**Issue by mikestead** [back2dos/tinkerbell#16]
Hey just wondering which licence this code is under? It would be good if it was in there with the source.

Nice library!

Mike

**Comment by back2dos** [comment]
Thanks. Well, let's just say it's free :)

I was actually aiming for MIT, but haxelib didn't allow it, so it's distributed under BSD there. As soon as that's possible, it'll all be MIT (or something along those lines) and I'll update the source code to mention that.

**Comment by Simn** [comment]
By now haxelib allows MIT.

**Comment by back2dos** [comment]
Well, then I have an exquisitely exciting task ahead of me :D

**Comment by mikestead** [comment]
:)

MIT or BSD is great, thanks for getting to this.

Just so you know, most companies (including the one I work for) won't go near OSS without a clear license so that's why I was requesting it.

**Comment by back2dos** [comment]
Hey Mike,

I intended to ask you earlier but kind of forgot. I now included a license.txt.
Personally I am no fan of having every source file preceded by 20 lines of license text. It adds unnecessary noise IMHO.

Still, if that's not good enough for whichever decision makers you're quarreling with, just tell me what exactly it is they need ;)

**Comment by mikestead** [comment]
That will do just fine cheers
