### ISSUE TITLE
@:read should be supported by @:forward

### ISSUE THREAD

**Issue by raould** [back2dos/tinkerbell#18]
class LevelSpec
implements tink.lang.Cls {
 @:read var ltype:Int = _; // only works with @:prop, not @:read.
}

class Level
implements tink.lang.Cls {
 @:read var index:Int = _;
 @:forward( ltype ) var levelSpec:LevelSpec = _;
}

class Test {
 public static function main() {
   var ls = new LevelSpec( -1 );
   var l = new Level( 0, ls );
   trace( l.ltype == -1 ); // ./Test.hx:9: characters 4-11 : Method
set_ltype required by property ltype is missing
 }
}

**Comment by back2dos** [comment]
I've just realized I have fixed this a while back but never pushed it. It's up on haxelib now ;)
