### ISSUE TITLE
methods sometimes don't get forwarded

### ISSUE THREAD

**Issue by raould** [back2dos/tinkerbell#19]
sometimes it fails to carry over certain things. so far has always
been methods, haven't seen it fail with vars. i even had a case where
it was working and then i have been doing major rework and it stopped
working. and then if i explicitly just add the field it works.

class X implements Cls {
 @:forward var y:Y = _;
 public function foobar() {
   callAMethodOnY(); // compile fails with "unknown identifier :
callAMethodOnY"
   y.callAMethodOnY(); // works
 }
}

**Comment by back2dos** [comment]
I'm pretty sure this is a duplicate of [#22](https://github.com/back2dos/tinkerbell/issues/22)

**Comment by raould** [comment]
ok
