### ISSUE TITLE
could property function names match what haxe does for "default"?

### ISSUE THREAD

**Issue by raould** [back2dos/tinkerbell#25]
it feels odd that if i have an interface that specifies properties, and want to use that with tink_lang, then i have to do something like:

var foo(get_foo,null):String

instead of just

var foo(default,null):String

**Comment by back2dos** [comment]
I think I'll just add support for interfaces, so that either way you write `@:read var foo:String;`

Would that work for you?

**Comment by raould** [comment]
sure, and it isn't a big stopping deal type issue overall anyway, probably :)

**Comment by back2dos** [comment]
Ok, @:read and @:write are now supported for interfaces. It should be noted though, that if `I implements Cls` and `A implements I`, it will also be affected by the @:autoBuild.

Also, to actually get this to work with haxelib, I had to delete prior versions of tink (didn't have the patience to delete one by one, so deleting all did the trick).
