### ISSUE TITLE
explain how / add support for "overloads" for @:read etc. 

### ISSUE THREAD

**Issue by jslenk-duffresearch** [back2dos/tinkerbell#28]
class Super uses tink_lang @:read var foo:String.
class Sub extends Super wants to change how foo is returned.

(i know, prefer composition over inheritance, but never the less...)

**Comment by back2dos** [comment]
I'm not sure I understand right, but overriding get_foo should do the trick, no?

**Comment by back2dos** [comment]
Can I close the ticket, or did you want something else entirely?

**Comment by jslenk-duffresearch** [comment]
i will try what you said, thanks! please close ok.
