### ISSUE TITLE
explain how / add support for structural type matches

### ISSUE THREAD

**Issue by jslenk-duffresearch** [back2dos/tinkerbell#29]
if i have a class that uses tink.lang.Cls and then has e.g. @:read var foo:String, and then i want it to match a typedef structural type, what is the right definition of the structural type?

typedef TFoo = { function get_foo():String; } seems to give me "the field get_foo() is not public".

**Comment by back2dos** [comment]
This should do it: typedef TFoo = { var foo(get_foo, null):String; }

**Comment by jslenk-duffresearch** [comment]
i just figured that out, too, thanks. was going to post here but then was confused that the issue disappeared, then realized it was closed already :-)
