### ISSUE TITLE
TypeTools.asTypePath() doesn't really return a TypePath

### ISSUE THREAD

**Issue by Simn** [back2dos/tinkerbell#3]
TypeTools.asTypePath() does actually return a ComplexType which happens to be a TPath. This is a bit misleading because one would expect to be able to use ENew("pack.Name".asTypePath(), []).

I would prefer the TypePath structure itself to be returned so it can be used for ENew and in other situations where a real TypePath is needed. If you want to keep the current behavior, the method name should be changed to asComplexType.

**Comment by back2dos** [comment]
Good point ;)

**Comment by Simn** [comment]
So is there any convenient way of getting an ENew?

**Comment by back2dos** [comment]
Yes. Have a look at TypeTools.asTypePath, TypeTools.instantiate and ExprTools.instantiate to see what suits your needs.
