### ISSUE TITLE
@:forward not work in wiki example

### ISSUE THREAD

**Issue by sonygod** [back2dos/tinkerbell#39]
class Stack implements tink.lang.Cls {
       @:forward(push, pop, iterator, length) var elements:Array;
       public function new() {
            this.elements = [];

```
   }
```

  }

//
src/Stack.hx:9: characters 9-16 : Invalid number of type parameters for Array
C:\Motion-Twin\haxe\lib\tink_lang/0,4,0/tink/lang/Cls.hx:10: characters 3-12 : Build failure
src/Stack.hx:9: characters 46-65 : Invalid number of type parameters for Array
src/Stack.hx:11: characters 12-25 : Stack has no field elements

**Comment by SimonRichardson** [comment]
Is this not as simple as ?

```
class Stack<T> implements tink.lang.Cls {
@:forward(push, pop, iterator, length) var elements:Array<T>;
public function new() {
this.elements = [];

   }
}
```

**Comment by sonygod** [comment]
thank you ,it's work now !

**Comment by back2dos** [comment]
Thanks for noticing!
I updated in the wiki, but feel free to do so yourself ;)
