### ISSUE TITLE
question about generate function with parameters

### ISSUE THREAD

**Issue by sonygod** [back2dos/tinkerbell#42]
<code>import test.test.Testx;

using tink.macro.tools.MacroTools;

class Main {
    static function main() {

```
//src/Main.hx:14: characters 2-14 : Invalid number of type parameters for test.test.Testx
 times_tink();

}   

//the tink way
@:macro static function times_tink():Expr {



    var inst = ENew( { pack:["test","test"], name:"Testx", params:[TPType("hello".asComplexType())] }, []).at();


    return  inst;

}  
```

}
/**
- package test.test;

class Testx
{
    public var a = 1;
    public function new(?target:String)
    {
        trace("hello--"+target);
    }

}
**/
</code>
what's wrong with my caller?thanks.

**Comment by back2dos** [comment]
You are mistaking type _parameters_ for constructor _arguments_. It should be either of these:

```
ENew( { pack:["test","test"], name:"Testx", params:[] }, ["hello".toExpr()]).at();

"test.test.Testx".instantiate(["hello".toExpr()]);

macro new test.test.Testx("hello");
```

**Comment by sonygod** [comment]
how about this 

@:macro static function testFunction():Expr {
        var f = (function say(age:Int,name:String):String { return name+age; }) .toExpr();
        return f.func(["age".toArg("Int".asComplexType()),"name".toArg("String".asComplexType())], "String".asComplexType()).toExpr();
    }

and the generate code 

function(age : int,name : String) : String {
                return null;
            }

what's wrong ?
