### ISSUE TITLE
question :Is that possible auto convert UInt to Int?

### ISSUE THREAD

**Issue by sonygod** [back2dos/tinkerbell#43]
such like this code 
    #if flash
    static public function createBitmap(Width:UInt, Height:UInt, Color:UInt, ?Unique:Bool = false, ?Key:String = null):BitmapData
    #else
    static public function createBitmap(Width:Int, Height:Int, Color:BitmapInt32, ?Unique:Bool = false, ?Key:String = null):BitmapData

every function need to write twice is waste..
I want  width:@UInt, Height:@Uint,,is that possible?
thanks.

**Comment by back2dos** [comment]
This should do the trick:

```
typedef MyInt = #if flash UInt #else Int #end;

static public function createBitmap(Width:MyInt, Height:MyInt, Color:MyInt, ?Unique:Bool = false, ?Key:String = null):BitmapData
```
