### ISSUE TITLE
renaming when forwarding

### ISSUE THREAD

**Issue by raould** [back2dos/tinkerbell#47]
i wish there were (i didn't see such a think in the docs) a simple concise way to rename things for forwarding, like:
class pdq implements tink.lang.Cls { @:forw (foo=bar) var xyz; }
means:
pdq.foo calls xyz.bar.

**Comment by back2dos** [comment]
This is currently not possible, but seems worth adding ;)

**Comment by back2dos** [comment]
If you still feel you need this, please open an issue here: https://github.com/haxetink/tink_lang/issues
