### ISSUE TITLE
Some Error

### ISSUE THREAD

**Issue by alijaya** [back2dos/tinkerbell#6]
I got this error, what is it?

/usr/lib/haxe/lib/tink_macros/0,2,2/tink/macro/tools/TypeTools.hx:92: characters 10-15 : This constructor is not part of the enum haxe.macro.Type
/usr/lib/haxe/lib/tink_macros/0,2,2/tink/macro/tools/TypeTools.hx:84: lines 84-103 : haxe.macro.ComplexType should be Void
/usr/lib/haxe/lib/tink_macros/0,2,2/tink/macro/tools/TypeTools.hx:84: lines 84-103 : Void should be haxe.macro.ComplexType
/usr/lib/haxe/lib/tink_lang/0,1,0/tink/lang/macros/Forward.hx:138: characters 4-11 : Missing ;
/usr/lib/haxe/lib/tink_lang/0,1,0/tink/lang/macros/Forward.hx:138: characters 11-12 : Unexpected :
/usr/lib/haxe/lib/tink_lang/0,1,0/tink/lang/macros/Forward.hx:138: characters 11-12 : Unexpected :

**Comment by back2dos** [comment]
This error occurs due to macro API changes from haXe 2.08 to 2.09. You can expect 2.09 to be released before the WWX (April 14th). Until then, you will have to build haXe yourself or use a nightly build.

**Comment by alijaya** [comment]
oh thanks XD
