### ISSUE TITLE
NodesTest.hx is broken since haxe r4371

### ISSUE THREAD

**Issue by Simn** [back2dos/tinkerbell#9]
The offending line is
'The habitants of ${$em(town.name)} are:',
with the error being "Unknown identifier : $em"

**Comment by back2dos** [comment]
Can't get my hands on a recent build, but the problem should be fixed now. Before, I had kind of hacked this together with Format.format and intercepting Context.parse. Now I just copied and customized the code.

Can you please confirm this is working?

**Comment by Simn** [comment]
Yes, it works, thanks!
